### PR TITLE
fix(package-lock): package-lock json added

### PR DESCRIPTION
**Pull request by nutboltu**

### CODE REVIEW

**Comment by superhit0** [comment]
I am not sure, if we need `package-lock` for this repo.

**Comment by nutboltu** [comment]
@superhit0 As we are installing packages we should lock the package.

**Comment by patw0929** [comment]
Actually I use `yarn` only. But I think `package-lock.json` is also useful for those who use npm v5.
We must remember to update both `yarn.lock` & `package-lock.json` in the future if we want to support yarn & npm v5.
Any thought?

**Comment by superhit0** [comment]
I am not sure for adding `package-lock` or `yarn.lock` as of now. 

My reason for adding these lock files because to lock the dependencies for production because we don't know how or when the production will be used so we lock the dependencies so that it never breaks for the user.

But here we have only dev-dependencies and all of them would be used only in testing while PR submits or maybe during automation (if possible we prefer doing that).

But for now, do we even need them?


Correct me if I missed anything?

**Comment by nutboltu** [comment]
@patw0929 , @superhit0 
My thought of adding package-lock is to keep a specific version in the test run. Though they are devDependencies but it will help the `travis` build to install the locked package and run the test. Otherwise it might break the test. As it's not a big deal right now, I am closing the PR

**Pull request closed without merging**
