### PR TITLE
Upgrading Libphonenumber version to 8.10.2

### PR DESCRIPTION
**Pull request by superhit0**
- Bumping the version to google libphonenumber `8.10.2`
- Added tests for libphonenumber
@nutboltu @patw0929

### CODE REVIEW

**Comment by patw0929** [comment]
LGTM! Thanks a lot!
Is it work nicely with `react-intl-tel-input`?

And about the test framework, I prefer to `jest` because it just works out of the box. (no need to install `chai` or some other assertion lib)
Any suggestion?

**Comment by superhit0** [comment]
- Is it work nicely with react-intl-tel-input? --> `Give me a day to confirm`

- And about the test framework, I prefer to jest because it just works out of the box. (no need to install chai or some other assertion lib) --> `I prefer chai just because of the assertion functions they provide but anyways this is test code and would never be pushed to production anyways, I think we can use it. For mocha, if you want I can move it to jest but I would suggest keeping chai`

**Comment by superhit0** [comment]
Moved from Mocha to Jest

**Comment by superhit0** [comment]
Test Result from reactintltelinput

```
Test Suites: 4 passed, 4 total
Tests:       1 skipped, 76 passed, 77 total

```

**Pull request merged**
